version: '3'

services:
  mongo:
    build:            # não é image, pois estamos lidando com imagens customizada (nossas)
      context: .      # onde se encontra o nosso dockerfile desse serviço
      dockerfile: mongodb.dockerfile
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - rede-aplicacao

  mongo-express:
    build: 
      context: .
      dockerfile: mongo-express.dockerfile
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - rede-aplicacao
    depends_on:
      - mongo

  node1:
    build: 
      context: .
      dockerfile: app.dockerfile
    container_name: node1
    ports:
      - 3001:3000
    networks:
      - rede-aplicacao
    depends_on:
      - mongo

  node2:
    build: 
      context: .
      dockerfile: app.dockerfile
    container_name: node2
    ports:
      - 3002:3000
    networks:
      - rede-aplicacao
    depends_on:
      - mongo

  node3:
    build: 
      context: .
      dockerfile: app.dockerfile
    container_name: node3
    ports:
      - 3003:3000
    networks:
      - rede-aplicacao
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    networks:
      - rede-aplicacao
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2
      - node3

volumes:
  mongo-volume:

networks:
  rede-aplicacao:
    driver: bridge